### ISSUE TITLE
Have darwin CI store artifacts locally

### ISSUE THREAD

**Issue by brryan** [lanl/artemis#16]
The Darwin CI script reports the result of the test run to github, but it does not store any artifacts from the run, which would be useful for diagnosing failures. 

I don't know how to send artifacts from Darwin to github. But one possibility would be to have each CI run create a `ci_darwin_volta-x86_PR[#]_[slurm job ID]` directory in `artemis/tst` (by default, optionally overwritten) that includes the slurm output file already created, and also all the artifacts created by the testing. 

I will get to this after:
- [ ] PR #14 is merged

**Comment by adamdempsey90** [comment]
One other related thing. I don't know what the log file gets us over print statements. The slurm output file has everything we need to diagnose what happened except for some of the logging comments (e.g., density for this test is xx which is outside the tolerance) that could just be normal print statements.

**Comment by brryan** [comment]
> One other related thing. I don't know what the log file gets us over print statements. The slurm output file has everything we need to diagnose what happened except for some of the logging comments (e.g., density for this test is xx which is outside the tolerance) that could just be normal print statements.

I agree in this case the logfile and slurm output should be mostly (but maybe not exactly?) redundant, but that's a special case of the slurm-based workflow, and since in my proposal we'd already be creating a `ci_[partition]_pr[#]_[slurm job id]` directory it shouldn't cost us anything to just dump the logfile in there as well, which someone may find convenient at some point if they are comparing a slurm run with a non-slurm `run_tests.py` call
